apiVersion: v1
kind: Service
metadata:
    name: loadwalaservice
spec:
  type: Loadbalancer
  selector:
       app: myapp
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     